package controller;

import domain.Lotto;
import domain.LottoNumber;
import domain.Lottos;
import view.ErrorView;
import view.InputView;
import view.ResultView;

import java.util.ArrayList;
import java.util.List;

public class LottoController {
    private final InputView inputView;
    private final ResultView resultView;
    private final ErrorView errorView;

    public LottoController(InputView inputView, ResultView resultView, ErrorView errorView) {
        this.inputView = inputView;
        this.resultView = resultView;
        this.errorView = errorView;
    }

    public void run() {
        int purchaseAmount = getValidPurchaseAmount();
        int manualPurchaseCount = getValidateManualPurchaseCount();

        Lottos lottos = new Lottos(purchaseAmount, manualPurchaseCount);

        List<Lotto> autoGeneratedLottos = lottos.getLottos();
        List<Lotto> manualyPurchasedLottos = getValidateManuallyPurchasedLotto(manualPurchaseCount);

        List<Lotto> allLottos = new ArrayList<>();
        allLottos.addAll(autoGeneratedLottos);
        allLottos.addAll(manualyPurchasedLottos);

        resultView.printAllLottos(autoGeneratedLottos);

        Lotto winningLotto = getValidWinningLotto();
        LottoNumber bonusBall = getValidateBonusBall();

        resultView.printWinningLottoStatistics(purchaseAmount, winningLotto.getNumbers(), allLottos, bonusBall);
    }

    private int getValidPurchaseAmount() {
        try {
            return inputView.getPurchaseAmount();
        } catch (NumberFormatException e) {
            errorView.printErrorMessage("숫자만 입력해주세요!");
            return getValidPurchaseAmount();
        } catch (IllegalArgumentException e) {
            errorView.printErrorMessage(e.getMessage());
            return getValidPurchaseAmount();
        }
    }

    private int getValidateManualPurchaseCount() {
        try {
            return inputView.getManualPurchaseCount();
        } catch (IllegalArgumentException e) {
            errorView.printErrorMessage(e.getMessage());
            return getValidateManualPurchaseCount();
        }
    }

    private List<Lotto> getValidateManuallyPurchasedLotto(int manualPurchaseAmount) {
        try {
            return inputView.getManuallyPurchasedLottos(manualPurchaseAmount);
        } catch (NumberFormatException e) {
            errorView.printErrorMessage(e.getMessage());
            return getValidateManuallyPurchasedLotto(manualPurchaseAmount);
        }
    }

    private Lotto getValidWinningLotto() {
        try {
            List<LottoNumber> numbers = inputView.getWinningNumbers();
            return new Lotto(numbers);
        } catch (NumberFormatException e) {
            errorView.printErrorMessage("숫자만 입력해주세요!");
            return getValidWinningLotto();
        } catch (IllegalArgumentException e) {
            errorView.printErrorMessage(e.getMessage());
            return getValidWinningLotto();
        }
    }

    private LottoNumber getValidateBonusBall() {
        try {
            return inputView.getBonusBall();
        } catch (IllegalArgumentException e) {
            errorView.printErrorMessage(e.getMessage());
            return getValidateBonusBall();
        }
    }
}
