package view;

import domain.Lotto;
import domain.LottoNumber;
import domain.MatchResult;
import domain.WinningLotto;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class ResultView {

    private static final String MATCH_COUNT_MESSAGE = "개 일치";
    private static final String MESSAGE_BEFORE_REWARD = "(";
    private static final String MESSAGE_AFTER_REWARD = "원)- ";
    private static final String MESSAGE_AFTER_COUNT = "개";


    WinningLotto winningLotto = new WinningLotto();

    public void printAllLottos(List<Lotto> allLottos, int manualPurchaseCount) {
        int lottoCount = allLottos.size();
        int autoGeneratedLottoCount = lottoCount - manualPurchaseCount;

        System.out.println("수동으로 " + manualPurchaseCount + "장, 자동으로" + autoGeneratedLottoCount + "개를 구매했습니다.");

        for (Lotto lotto : allLottos) {
            System.out.println(lotto.getNumbers().toString());
        }
    }

    public void printWinningLottoStatistics(final int purchaseAmount, List<LottoNumber> winningNumbers, List<Lotto> allLottos, LottoNumber bonusBall) {
        HashMap<MatchResult, Integer> resultMap = winningLotto.getMatchResult(allLottos, winningNumbers, bonusBall);

        System.out.println("당첨 통계");
        System.out.println("-----------");

        for (MatchResult result : MatchResult.values()) {
            String bonusMessage = "";

            if (result == MatchResult.FIVE_WITH_BONUS) {
                bonusMessage = ", 보너스 볼 일치";
            }
            int matchStandardCount = result.getMatchCount();
            if (matchStandardCount == 0) {
                continue;
            }

            int matchUnitReward = result.getMatchReward();
            int myMatchCount = resultMap.getOrDefault(result, 0);

            System.out.println(matchStandardCount + MATCH_COUNT_MESSAGE + bonusMessage + MESSAGE_BEFORE_REWARD + matchUnitReward + MESSAGE_AFTER_REWARD + myMatchCount + MESSAGE_AFTER_COUNT);
        }

        double profitRate = winningLotto.getLottoProfitRate(resultMap, purchaseAmount);
        System.out.println("총 수익률은 " + String.format("%.2f", profitRate) + "입니다.");
    }
}
